[book]
authors = ["Muhammad Ridho"]
language = "en"
multilingual = false
src = "src"
title = "Concurrency Terapan dengan Bahasa Pemrograman Rust"

[output.html]
git-repository-url = "https://github.com/datafy-id/concurrency-terapan-pemrograman-rust"
site-url = "https://datafy-id.github.io/concurrency-terapan-pemrograman-rust/"
